version: "3.7"

services:

  flask:
    build: ./flask
    container_name: fe_client_flask
    restart: always
    environment:
      - APP_NAME=flask
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: fe_client_nginx
    restart: always
    ports:
      - "80:80"

networks:
  default:
    external:
      name: backend_private_network